### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-200-fall-2023/dynamo-dispatcher-assignment#1]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## TODOs

- [x] adder&#x2F;program.S contains no TODOs
- [x] adder&#x2F;ops.S contains no TODOs
- [ ] dynamo&#x2F;program.S contains no TODOs
- [ ] dynamo&#x2F;dispatch.S contains no TODOs
- [ ] sifter&#x2F;sifter.S contains no TODOs
- [ ] sifter&#x2F;program.S contains no TODOs
- [ ] docs&#x2F;report.md contains no TODOs

## ARMv6 Assembly

- [x] adder&#x2F;program.S contains BL instruction to add subroutine
- [x] adder&#x2F;program.S contains a PUSH instruction to add LR to stack
- [x] adder&#x2F;program.S contains a POP instruction remove LR from stack to register
- [x] adder&#x2F;program.S contains a BX instruction to return to value from LR
- [ ] dynamo&#x2F;program.S contains BL instruction to dispatch subroutine
- [ ] dynamo&#x2F;dispatch.S contains sufficient PUSH instructions to add values to the stack
- [ ] dynamo&#x2F;dispatch.S contains sufficient POP instructions to add values to the stack
- [ ] dynamo&#x2F;dispatch.S uses LSR to shift a register incrementally
- [ ] dynamo&#x2F;dispatch.S uses adequate BX instructions to branch to appropriate loops
- [ ] dynamo&#x2F;dispatch.S uses CMP instructions to evaluate conditional logic
- [ ] dynamo&#x2F;dispatch.S uses traditional branching instructions to branch on logic
- [ ] sifter&#x2F;program.S branches and links to sifter
- [ ] sifter&#x2F;sifter.S POPs from the stack
- [ ] sifter&#x2F;sifter.S PUSHes from the stack
- [ ] sifter&#x2F;sifter.S uses BX to jump to appropriate point
- [x] sifter&#x2F;sifter.S compares values to branch appropriately
- [ ] sifter&#x2F;sifter.S compares uses branch and link to return to appropriate point in previous subroutine

## Percent complete

Based on the checks achieved, this assignment is `29%` complete.
